name = "Remember"
license = "NYSL"
licenselink = "https://github.com/5000164/remember/blob/master/LICENSE.txt"
description = ""
homepage = "https://github.com/5000164/remember"
tags = []
features = []
min_version = "0.26"

[author]
name = "Hiroshi SUGAWARA"
homepage = "https://github.com/5000164"
